import Footer from "./components/footer";
import Navbar from "./components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CryptoWeb",
  description: "Generated by Diwansh Gupta",
  // images: "/photo-1621504450181-5d356f61d307.avif",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta property="og:image" content="/favicon.ico" />
      </Head>

      <body className={`inter.className  anigrademate`}>
        {" "}
        <Navbar />
        <div className=" md:ml-64"> {children}</div>
        <Footer />
      </body>
    </html>
  );
}
